[login]
email = 'user@name.com'
password = 'password'

[slack]
channel_id = '#####'
token = '#######'

[logging]
filename = 'automation_log.txt'
level = 'logging.INFO'
format= '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

[meta_pages]
base = 'meta_base'
allpharm = 'allpharm'
realtime = 'realtime'
vet_orders = 'vet_orders'

[floofy_pages]
base = 'floofy_base'
intake_ny = 'intake'
intake_fl = 'intake'
intake_la = 'intake'